<?php

namespace Tuforti\MoneyToWords\Grammar;

use Tuforti\MoneyToWords\Contracts\Cache;
use Tuforti\MoneyToWords\Languages as Language;
use Tuforti\MoneyToWords\Grammar\DigitDictionary;
use Tuforti\MoneyToWords\Helpers\StringProcessing as Str;

class SentenceGenerator
{
    /**
     * Global cache used for storing generated sentences.
     */
    static $cache = Cache::class;

    /**
     * Set the global cache used for senetence generator
     *
     * @param $cache
     * @return void
     */
    public static function setCache($cache)
    {
        static::$cache = $cache;
    }

    /**
     * Convert a given money value in greek numbers to english sentence.
     *
     * @param String $moneyValue Money value to convert
     * 
     * @return String
     */
    public static function generateSentence($moneyValue)
    {
        $sentence = static::$cache::get($moneyValue, Language::ENGLISH);
        if ($sentence) return $sentence;

        $moneyValueArray = Str::splitIntoArrayOfSizeThree(strval(intval($moneyValue)));
        $sentence = self::_generateSentence($moneyValueArray);

        static::$cache::set($moneyValue, Language::ENGLISH, $sentence);
        return $sentence;
    }

    /**
     * Convert a given money value whose already prepared into a set of 3.
     * e.g. [003,472,747], [045,532,453]
     * 
     * @param Array $moneyValueArray Money value in array to convert to words
     * 
     * @return String
     */
    private static function _generateSentence(array $moneyValueArray)
    {
        $sentence = "";
        $arraySize = count($moneyValueArray);
        for ($i = 0; $i < $arraySize; $i++) {
            $index = $arraySize - $i - 1;
            $groupValue = DigitDictionary::convertHundredthDigit($index);
            $hundredth = DigitDictionary::convertUnitDigit($moneyValueArray[$i][0]);
            $tensAndUnit = DigitDictionary::convertTensAndUnitDigit(
                $moneyValueArray[$i][1] . $moneyValueArray[$i][2]
            );

            if ($hundredth !== "") {
                $hundredth .= " hundred";
            }

            if ($tensAndUnit !== "" && $hundredth !== "") {
                $tensAndUnit = "and " . $tensAndUnit;
            }

            if ($hundredth == "") {
                $sentence .= "{$tensAndUnit} ";
            } else {
                $sentence .= "{$hundredth} {$tensAndUnit} ";
            }

            if ($groupValue != "" && ($tensAndUnit != "" || $hundredth != "")) {
                $sentence = rtrim($sentence) . " " . $groupValue . ", ";
            }
        }

        return static::_trimGeneratedSentence($sentence);
    }

    /**
     * Trim end of sentence generated by removing unwanted 
     * characters, symbols, and whitespaces.
     *
     * @param String $sentence
     * @return String
     */
    private static function _trimGeneratedSentence($sentence): string
    {
        $sentence = rtrim($sentence);
        if (Str::endsWith($sentence, ",")) {
            $sentence = substr($sentence, 0, strlen($sentence) - 1);
        }

        return trim($sentence);
    }
}
